apiVersion: apps/v1
kind: Deployment
metadata:
  name: koogle-f-deploy
  namespace: koogle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koogle-f
  template:
    metadata:
      labels:
        app: koogle-f
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: koogle-f
          image: workirostub/koogle:front-server
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: koogle-f-http
---
apiVersion: v1
kind: Service
metadata:
  name: koogle-f-svc
  namespace: koogle
spec:
  type: NodePort
  selector:
    app: koogle-f
  ports:
    - protocol: TCP
      port: 80
      targetPort: koogle-f-http